version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_dev
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: pass_dev
      POSTGRES_DB: db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 15

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass
    ports:
      - "8081:80"
    depends_on:
      - postgres

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=8080
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: